import Foundation

extension LanguageModule {
    public static let german = LanguageModule(
        id: "de", name: "German", nativeName: "Deutsch", variety: "Germany", locale: "de-DE",
        greeting: "Hallo!", greetingWord: "hallo",
        speechGuidance: "Use clear, natural Standard German as spoken in Germany. The learner is usually a care worker from abroad preparing for or working in German healthcare, so favour clear everyday and workplace German. Use Sie with patients, relatives and doctors and du among colleagues where natural. Accept valid Austrian, Swiss and other regional pronunciation, vocabulary and grammar. Do not treat a regional difference or a non-native accent alone as an error. Correct pronunciation only when supported by the audio, not a transcript alone. Care situations are role-play: if asked for a real medical, dosage or legal decision, stay in the role-play and point to the responsible doctor and the ward’s standards instead.",
        writingGuidance: "Use standard German spelling, noun capitalization, umlauts and ß. Accept Swiss ss spellings and valid regional wording. Match the register to the situation.",
        lemmaGuidance: "Give nouns with their singular article and verbs in the infinitive, for example das Haus, die Straße and sprechen. Preserve umlauts and ß. Keep separable verbs such as aufstehen and reflexive verbs such as sich erinnern together as dictionary entries, while quoting the learner's actual word order exactly.",
        teachingFocus: [
            "Greetings, introducing yourself on the ward and useful everyday chunks such as ich heiße, ich bin die Pflegekraft and ich möchte.",
            "Everyday questions to patients and colleagues, body parts and complaints, Sie and du, grammatical gender, present tense, verb-second word order and common accusative objects.",
            "Connected reports such as a short handover, conversational past tenses (Perfekt and Präteritum), dative uses, separable verbs and familiar care situations.",
            "Reasons and opinions, subordinate-clause word order, relative clauses and polite Konjunktiv II requests to patients and relatives.",
            "Nuance, hypothetical situations, passive voice in report style, technical versus everyday wording and register, as needed for B2 and a Fachsprachprüfung.",
            "Flexible advanced professional discussion with precise, natural German and appropriate tone."
        ],
        topicPlaceholder: "Übergabe, Visite, Angehörige, Alltag in Deutschland…",
        lookupUnavailableReply: "Das konnte ich gerade nicht überprüfen. Wenn du möchtest, können wir allgemein über das Thema sprechen.",
        themeOverrides: [
            "handover": .init("handover", "Die Übergabe", "Was die nächste Schicht wissen muss", "arrow.left.arrow.right", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a nurse colleague on a German ward receiving the Dienstübergabe. Let the learner report structured, similar to SBAR: Situation, Hintergrund, Einschätzung, Empfehlung. Use terms such as Vitalzeichen, Dekubitus, Mobilisation and Pflegebericht. Colleagues use du; ask short follow-up questions.", 0),
            "admission": .init("admission", "Aufnahmegespräch", "Eine neue Patientin kennenlernen", "person.text.rectangle", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a patient just admitted to a German hospital ward. The learner uses Sie and asks about Beschwerden, Vorerkrankungen, Allergien, Medikamente and daily needs. Answer with everyday words, not medical jargon.", 1),
            "medication": .init("medication", "Medikamentengabe", "Erklären, was und wann", "pills", "Care work", "Rollenspiel, keine echte medizinische, Dosierungs- oder Rechtsberatung. You are a patient in Germany receiving your medication. The learner explains using Sie what it is for and when to take it, then asks whether you have questions. Ask one simple question back; if a real dosage question comes up, refer to the doctor.", 2),
            "relatives": .init("relatives", "Angehörige am Telefon", "Höflich, klar und diskret", "phone", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a worried relative calling a German ward. The learner uses Sie, informs politely, stays calm and respects Datenschutz and Schweigepflicht by not sharing details they may not give. Practise polite refusals with Konjunktiv II.", 3),
            "wardround": .init("wardround", "Visite", "Kurz, präzise, auf den Punkt", "stethoscope", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a doctor on the Visite in a German hospital. The learner uses Sie and reports briefly on a patient: Vitalzeichen, Veränderungen, offene Fragen. Ask for clarification and switch between Fachsprache and Alltagssprache.", 0),
            "pain": .init("pain", "Wo tut es weh?", "Schmerzen ruhig erfassen", "heart.text.square", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a patient in a German care setting who is in pain. The learner uses Sie and asks where it hurts, how strong on the Schmerzskala from 0 to 10 and what kind of pain, then reassures you and explains the next step.", 1),
            "bodycare": .init("bodycare", "Grundpflege", "Schritt für Schritt, mit Zustimmung", "figure.walk", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a patient in Germany being helped with Körperpflege, Anziehen or Mobilisation. The learner uses Sie, explains each step, asks for your Einverständnis and encourages you kindly.", 2),
            "emergency": .init("emergency", "Sturz melden", "Knapp und klar unter Druck", "exclamationmark.triangle", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a colleague on a German ward receiving a report about a Sturz or a sudden change in a patient. Let the learner report briefly and clearly, then ask short questions about what happened, the Vitalzeichen and what has been done. Colleagues use du.", 3),
            "phonecall": .init("phonecall", "Am Telefon", "Bestellen, nachfragen, buchstabieren", "phone.arrow.up.right", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are the Apotheke or another Station on the phone in Germany. The learner uses Sie, places an order, asks a question or passes on information. Ask them to spell a name with the German spelling alphabet and confirm details.", 0),
            "documentation": .init("documentation", "Pflegebericht schreiben", "Kurze Sätze, Vergangenheit", "doc.text", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a colleague helping the learner write a Pflegebericht in Germany. Let them describe what they observed and did in short report sentences in Präteritum or Perfekt and suggest clearer, more formal wording.", 1),
            "dementia": .init("dementia", "Ein ruhiges Gespräch", "Einfache Worte, Geduld, Wärme", "leaf", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are an older person with dementia in a German care home, a little confused about time and place. The learner uses Sie, simple short sentences, patience and a calm, validating tone without correcting you harshly.", 2),
            "discharge": .init("discharge", "Entlassungsgespräch", "Anweisungen und nächste Schritte", "door.left.hand.open", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a patient about to be discharged from a German hospital. The learner uses Sie and explains next steps, Termine, Hausarzt and what to watch for at home, then asks questions to check you understood.", 3),
            "team": .init("team", "Im Team", "Dienstplan, Bitten, kleine Konflikte", "person.3", "Care work", "Rollenspiel, keine echte medizinische Beratung. You are a colleague in a German care team; colleagues use du. Let the learner ask for a Diensttausch, decline politely or resolve a small disagreement in a friendly, respectful way.", 0),
            "coffee": .init("coffee", "Ein Kaffee?", "Something warm, please", "cup.and.saucer", "Everyday", "Meet in a neighbourhood café in Germany. Order a drink and chat. Use polite greetings with staff and follow the learner's interests.", 0),
            "groceries": .init("groceries", "Auf dem Markt", "A little of everything", "basket", "Everyday", "Shop at a weekly market in Germany. Practise quantities, prices and polite requests, accepting regional names for foods.", 2),
            "travel": .init("travel", "Unterwegs", "A ticket to somewhere", "tram", "Everyday", "Plan a trip in Germany. Discuss transport, directions and tickets without inventing current schedules.", 1),
            "cabin": .init("cabin", "A weekend away", "A change of scene", "mountain.2", "Local life", "Plan an imagined weekend in a German-speaking place. Choose a city, coast or countryside together and discuss practical plans.", 2),
            "traditions": .init("traditions", "Feierabend", "After the working day", "flag", "Local life", "Talk about routines after work and local customs in Germany. Compare the learner's experiences without treating German-speaking cultures as uniform.", 2)
        ]
    )
}
